### ISSUE TITLE
[REFACTOR] 함수 타입 중 ()=>{}로 선언한 부분을 void로 변경

### ISSUE THREAD

**Issue by SeojinSeojin** [boostcampwm-2021/web09-Duxcord#196]
## Description

`()=>{}`로 타입을 먹여놓은 함수들을 `Function`으로 변경하기

## To Dos
- [ ] `()=>{}`로 타입을 먹여놓은 함수들을 싹 다 발견해서 Function으로 변경하기

**Comment by superLipbalm** [comment]
타이핑을 잘 하자 타이핑타이핑👨‍💻👩‍💻
