### ISSUE TITLE
[BUG] 모달들의 확인, 닫기(X) 버튼의 커서 스타일이 빠져있습니다

### ISSUE THREAD

**Issue by superLipbalm** [boostcampwm-2021/web09-Duxcord#236]
## Description

모달들의 확인, 닫기(X) 버튼의 커서 스타일이 빠져있습니다!

## To Reproduce

1. 확인, 닫기 버튼들에 마우스를 올려도 커서가 안바뀜!
2. 채널 생성 모달의 채널 유형 선택도 커서 안바뀝니다!

## Expected behavior

커서가 손가락 모양(pointer)로 바뀌어야합니다!

**Comment by SeojinSeojin** [comment]
🍯 이슈 하나 추가..!! 많이많이 발견해주세용
