### ISSUE TITLE
[BUG] 채널 선택시 간헐적으로 채널 리스트순서가 역순으로 출력되는 경우

### ISSUE THREAD

**Issue by superLipbalm** [boostcampwm-2021/web09-Duxcord#242]
## Description

채널리스트에서 채널을 선택하다 보면 가끔 채널이 역순으로 출력됩니다.
## To Reproduce

1. 채널리스트에서 채널을 마구마구 클릭한다
2. 채널이 역순으로 출력된다
3. 다른 채널을 다시 누르거나, 새로고침 또는 다른창을 포커스 하다 오면 원상복구됨!

## Expected behavior

채널 순서가 늘 같아야합니다!

## Screenshots

![image](https://user-images.githubusercontent.com/77329061/142095620-910c239f-b0ea-4005-afa0-592364be75e6.png)

**Comment by jiho-bae** [comment]
저는 우선 노션에 따로 정리하고 있었는데, 이렇게 버그랑 개선사항들 이슈로 등록해두는거 너무 좋네요.🌝👍👍👍

**Comment by superLipbalm** [comment]
> 저는 우선 노션에 따로 정리하고 있었는데, 이렇게 버그랑 개선사항들 이슈로 등록해두는거 너무 좋네요.🌝👍👍👍

감사합니다!
이런식으로 이슈 등록해 놓고 PR링크해 놓으면 무엇이 문제였고 어떻게 해결했는지 나중에 보게되더라도 쉽게 알 수 있어 좋은 것 같아요!
방법을 제안해주신 갓서진님... 너무 감사하네요🙇‍♂️
그리고 저는 사실 버그 이슈 안올리고 고친 경우가 많아서 반성하게 되네요ㅎㅎ;

**Comment by jiho-bae** [comment]
> > 저는 우선 노션에 따로 정리하고 있었는데, 이렇게 버그랑 개선사항들 이슈로 등록해두는거 너무 좋네요.🌝👍👍👍
> 
> 감사합니다! 이런식으로 이슈 등록해 놓고 PR링크해 놓으면 무엇이 문제였고 어떻게 해결했는지 나중에 보게되더라도 쉽게 알 수 있어 좋은 것 같아요! 방법을 제안해주신 갓서진님... 너무 감사하네요🙇‍♂️ 그리고 저는 사실 버그 이슈 안올리고 고친 경우가 많아서 반성하게 되네요ㅎㅎ;


마지막 말씀이 딱 저이기도 해서 무한공감입니다.ㅋㅋㅋㅋ ㅠㅠ
저희도 이제부터라도 기록좀 남기려구요. 자잘한 버그가 너무 많아서 이제 시작입니다 😭

**Comment by superLipbalm** [comment]
> > > 저는 우선 노션에 따로 정리하고 있었는데, 이렇게 버그랑 개선사항들 이슈로 등록해두는거 너무 좋네요.🌝👍👍👍
> > 
> > 
> > 감사합니다! 이런식으로 이슈 등록해 놓고 PR링크해 놓으면 무엇이 문제였고 어떻게 해결했는지 나중에 보게되더라도 쉽게 알 수 있어 좋은 것 같아요! 방법을 제안해주신 갓서진님... 너무 감사하네요🙇‍♂️ 그리고 저는 사실 버그 이슈 안올리고 고친 경우가 많아서 반성하게 되네요ㅎㅎ;
> 
> 마지막 말씀이 딱 저이기도 해서 무한공감입니다.ㅋㅋㅋㅋ ㅠㅠ 저희도 이제부터라도 기록좀 남기려구요. 자잘한 버그가 너무 많아서 이제 시작입니다 😭

마지막 벌레잡이도 화이팅입니다! 다들 잘하시니 금방 해결할 수 있을꺼에요! 🔥🔥🔥🔥🔥
