### ISSUE TITLE
[BUG] 화상 회의 중 카메라를 끌 경우 프로필 이미지가 조정되지 않은 채로 보이는 오류

### ISSUE THREAD

**Issue by SeojinSeojin** [boostcampwm-2021/web09-Duxcord#267]
## Description

화상 회의 중 카메라를 끌 경우 프로필 이미지가 조정되지 않은 채로 보입니다

## To Reproduce

1. 화상 회의 중 카메라를 끄면
2. 유저가 자신의 프로필 이미지를 300*300 이상으로 설정했을 경우
3. 이미지가 자신의 화면 밖으로 튀어나와 있는 채로 보입니다.

## Expected behavior

유저가 어느 크기로 설정하였던 간에 이미지는 자신의 화면 안에 보여야 합니다.

## Screenshots
![image](https://user-images.githubusercontent.com/48249505/142379049-d0434f53-1d94-4081-ab94-99859af34036.png)

**Comment by superLipbalm** [comment]
이미지 사이즈를 100px * 100px로 제한해 해결했읍니다!
