### ISSUE TITLE
[BUG] 그룹 탭바 길이 넘침

### ISSUE THREAD

**Issue by SeojinSeojin** [boostcampwm-2021/web09-Duxcord#99]
## Description

그룹에 많이 참가할 경우 아래로 그룹 탭바가 넘칩니다

## To Reproduce

1. 메인 페이지에서
2. 그룹에 여러개 참가하여 그룹을 채우는 div가 100vh보다 길어지면
3. 전체 화면에서 오버플로우가 생깁니다

## Expected behavior

오버플로우가 생기지 않고 스크롤되어야 합니다. 

## Screenshots
![image](https://user-images.githubusercontent.com/48249505/140271999-66a69db5-2c60-4f49-baf3-89a5628bfa23.png)

**Comment by superLipbalm** [comment]
GroupNav 스타일에 overflow-y: scroll 주면 될 것 같습니다
